#! /bin/sh -e
# Start/stop the onsite to RDV connection script.
#
### BEGIN INIT INFO
# Provides:          onsitedevscript 
# Required-Start:    $network $stunnel
# Required-Stop:     $network $stunnel
# Default-Start:     2
# Default-Stop:
# Short-Description: Automatic startup for onsite to RDV connection. 
# Description:       Automatically starts a connection to the RDV server
#                    as an onsite device, and persist in doing so (if
#                    connection is broken, it will re-try setting it up
#                    as long as this service is running)
### END INIT INFO

DAEMON="/home/pi/tunnelling-dev-scripts/onsitedev_script.sh" #ligne de commande du programme
daemon_OPT=""  #argument à utiliser par le programme
DAEMONUSER="root" #utilisateur du programme
daemon_NAME="onsitedevscript" #Nom du programme (doit être identique à l'exécutable)
PIDFILE='/var/run/onsitedevscript.pid'
INSTANCE_PIDFILE='/tmp/onsitedevscriptinstance.pid'

PATH="/sbin:/bin:/usr/sbin:/usr/bin" #Ne pas toucher

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

d_start () {
        log_daemon_msg "Starting system $daemon_NAME Daemon"
	start-stop-daemon --background --make-pidfile --pidfile $PIDFILE --name $daemon_NAME --start --quiet --chuid $DAEMONUSER --exec $DAEMON -- $daemon_OPT
        log_end_msg $?
}

d_stop () {
        log_daemon_msg "Stopping system $daemon_NAME Daemon"
        start-stop-daemon --pidfile $PIDFILE --stop --retry 5
	kill -2 `cat $INSTANCE_PIDFILE`
	log_end_msg $?
}

case "$1" in

        start|stop)
                d_${1}
                ;;

        restart|reload|force-reload)
                        d_stop
                        d_start
                ;;

        force-stop)
               d_stop
                killall -q $daemon_NAME || true
                sleep 2
                killall -q -9 $daemon_NAME || true
                ;;

        status)
                status_of_proc "$daemon_NAME" "$DAEMON" "system-wide $daemon_NAME" && exit 0 || exit $?
                ;;
        *)
                echo "Usage: /etc/init.d/$daemon_NAME {start|stop|force-stop|restart|reload|force-reload|status}"
                exit 1
                ;;
esac
exit 0
