#! /bin/sh -e
# Start/stop the secondary interface watcher on master devices.
#
### BEGIN INIT INFO
# Provides:          ifwatcher 
# Required-Start:    $udev
# Required-Stop:     $udev
# Default-Start:     2
# Default-Stop:
# Short-Description: Automatic watcher for connection of USB Ethernet interfaces. 
# Description:       Continuously checks connections of USB Ethernet interfaces
#                    or link change (up/down) to apply an IP configuration and
#                    run a DHCP service on them
### END INIT INFO

DAEMON="master-secondary-if-watcher.py"
daemon_OPT=""
DAEMONUSER="root"
daemon_NAME="ifwatcher"
PIDFILE='/var/run/master-secondary-if-watcher.pid'

PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin/"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

d_start () {
        log_daemon_msg "Starting $daemon_NAME daemon"
	start-stop-daemon --background --make-pidfile --pidfile $PIDFILE --name $daemon_NAME --start --quiet --chuid $DAEMONUSER --exec $DAEMON -- $daemon_OPT
        log_end_msg $?
}

d_stop () {
        log_daemon_msg "Stopping $daemon_NAME daemon"
        start-stop-daemon --pidfile $PIDFILE --stop --retry 5
	log_end_msg $?
}

case "$1" in

        start|stop)
                d_${1}
                ;;

        restart|reload|force-reload)
                        d_stop
                        d_start
                ;;

        force-stop)
               d_stop
                killall -q $DAEMON || true
                sleep 2
                killall -q -9 $DAEMON || true
                ;;

        status)
                status_of_proc "$daemon_NAME" "$DAEMON" "system-wide $daemon_NAME" && exit 0 || exit $?
                ;;
        *)
                echo "Usage: /etc/init.d/$daemon_NAME {start|stop|force-stop|restart|reload|force-reload|status}"
                exit 1
                ;;
esac
exit 0
